services:
  django:
    build:
     context: ./app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/app
    env_file:
      - ./app/env/.env
    expose:
      - 8000
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  postgres:
    # sprawdzi czy jest postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
        # volumy anonimowe
      - postgres:/var/lib/postgresql/data
    #zczyta dane do logowania db z pliku
    env_file:
      - ./app/env/.env
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - django

volumes:
  #docker stworzy anonimowy volume dla postgresa
  postgres:
