# Generated by Django 4.0.2 on 2022-02-21 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='location',
        ),
        migrations.AddField(
            model_name='flock',
            name='location',
            field=models.CharField(default='Lipnica Murowana', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupeday',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
