# Generated by Django 4.0.2 on 2022-03-21 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_weather_location_flock_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupeday',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.feed'),
        ),
        migrations.AlterField(
            model_name='coupeday',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.flock'),
        ),
    ]
